In [ ]:
my_list=[1,2,3]

In [ ]:
my_list

[1, 2, 3]

In [1]:
import numpy as np


In [ ]:
my_numpy_array = np.array(my_list)

In [ ]:
my_numpy_array

array([1, 2, 3])

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
my_mat_array=np.array(my_mat)

In [ ]:
my_mat_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#1st method to generate numpy arrays
#easily creating numpy arrays with arrange function
#we also use this function in loops for creating indexes:o now i got it:)
#start number,end number(not included due to start from zero) and step =kitna jump karna hy
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#2nd method(if you want to generate array of zero's)
#if you want 1d array one round bracket
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#if u want 2d array
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#if we want evenly spaced numbers over specified interval.
#do not confuse with arange and linspace.in linspace all numbers are between first number and last number.Mean number of points u want.
np.linspace(1,5,10)
#np.linspace(0,10,100)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
#identity matrix.It is vary useful when working with algebra
#because identity matrix is square matrix so only 1 argument cover 2d array(3*3 matrix in this case)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#numpy arrays with randonm values.their are lots of function for generating numpy arrays with random values of different type.
#rand():This create an array of given shape and create saple by uniform distribution over 0 to 1.
np.random.rand(5)#uniformly distributed values from 0 to 1

array([0.49421646, 0.15318558, 0.51142245, 0.04695202, 0.5157415 ])

In [ ]:
np.random.rand(5,5)

array([[0.24805974, 0.09125776, 0.07441826, 0.79854141, 0.63185811],
       [0.00988339, 0.38183586, 0.71696915, 0.1204404 , 0.61445652],
       [0.94110822, 0.82784306, 0.52518684, 0.97942337, 0.1382885 ],
       [0.38183817, 0.4821276 , 0.30964548, 0.28157193, 0.67183512],
       [0.67652773, 0.8517473 , 0.18437876, 0.80996459, 0.91222905]])

In [ ]:
#if u want to return a sample/samples from sample normal distribution or guassian distribution.
#np.random.randn(5)
np.random.randn(5,5)

array([[-1.98019762,  1.69429493,  0.5871325 , -0.66419408,  0.1349929 ],
       [-1.0375993 , -0.70848672,  1.42634442,  0.01056717, -1.03820724],
       [-0.79356606, -1.0343397 , -0.05891464,  0.00937905,  0.22388674],
       [-0.21067149, -0.89010009, -0.06923751,  0.16713812,  0.02847263],
       [-1.54788936, -0.93282339,  0.01607316,  0.83440852,  0.37018678]])

In [ ]:
#if we want any random number between range in which first is inclusive and 2nd is exclusive.
np.random.randint(0,100)#generate only one number
np.random.randint(0,100,6)

array([73, 35,  0,  5, 26, 49])

In [ ]:
#few useful methods of arrays
arr_1 = np.arange(25)
print(arr_1)
arr_2 = np.random.randint(0,50,10)
print(arr_2)
#1-reshape function
arr_1.reshape(5,5)#matrix must be complete other u get an error

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[33  1 25 43 32 30 45 30 21 35]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr_2.max()

45

In [ ]:
arr_2.min()

1

In [ ]:
arr_2.argmax()

6

In [ ]:
arr_2.argmin()

1

In [ ]:
#shape of vector
#it indicates 1d array
arr_1.shape

(25,)

In [ ]:
arr=arr_1.reshape(5,5)

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
#if you don't want to write np.random.rand() 
from numpy.random import randint
randint(1,50,5)

array([ 4, 31, 33, 29, 13])

**Numpy Arrray Indexing**

In [ ]:
arrr = np.arange(0,11)
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arrr[8]

8

In [ ]:
arrr[1:5]

array([1, 2, 3, 4])

In [ ]:
arrr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arrr[:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arrr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arrr[0:5]=100

In [ ]:
arrr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arrr=np.arange(0,11)

In [ ]:
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr = arrr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
#when we are slicing it shows chunk of that array and not copy that chunk n any var.so change in chunk is changge in original array
arrr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#if want to copy
arr_copy = arrr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[0:6]=100

In [ ]:
arrr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy
#original array is not changed

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

**Grabbing elements from 2d arrays**

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[0][0]

5

In [ ]:
arr_2d[0]

array([ 5, 10, 15])

In [ ]:
arr_2d[1][1]

25

In [ ]:
#we can also retrieve by single bracket
arr_2d[1,2]

30

In [ ]:
#now if we want sub matrix from a matrics(means more than one element)
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [ ]:
#conditional selection
arr = np.arange(1,11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bool_arr = arr > 5

In [ ]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [ ]:
#now do this in one step
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr_2d[1:4,2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

**Array operations
1-Array with array 
2-Array with sacalar
3-universal Array Functions**

In [ ]:
import numpy as np
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_s=arr*arr
arr_s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
np.max(arr)

10

In [ ]:
np.min(arr)

0

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [ ]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])